### PR TITLE
Update v3

### PR DESCRIPTION
**Pull request by langpavel**

### CODE REVIEW

**Comment by langpavel** [comment]
Please @metainfa, all is now published as 3.0.0. Check it out...
Thanks!

**Comment by langpavel** [comment]
I'm an asshole :-\

**Comment by metainfa** [comment]
Hi Pavel. I switched my projects to 3.0.0 - all OK.

But i found, that tests not runninng with `gulp-mocha` `4.0.1` I rollbacked to `gulp-mocha` `3.0.1`. Issue with `gulp-mocha` looks like this [154](https://github.com/sindresorhus/gulp-mocha/issues/154).  What about you?

**Comment by langpavel** [comment]
Hi, yes, tests was not running. This is why I unpublish v3.0.0. I will rework repository today and publish v3.0.1

**Comment by metainfa** [comment]
ok

**Pull request merged**
